" ------------------------------------------------------------------------------
" # Defaults
" ------------------------------------------------------------------------------

" Vim 8 defaults
" For more info, see :help defaults.vim
unlet! skip_defaults_vim
silent! source $VIMRUNTIME/defaults.vim

" ------------------------------------------------------------------------------
" # Sourcing
" ------------------------------------------------------------------------------

" Source plugins
call plug#begin('~/.vim/plugged')
  source ~/.dotfiles/vim/plugins.vim
call plug#end()

call sourcery#source()
